version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-new-demo-bucket1"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jw7tp7bfu89q"
s3_prefix = "s3-new-demo-bucket1"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
