AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ProductCRUDFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.productHandler
      Runtime: nodejs12.x
      Events:
        USserGetAPI:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: ANY
        
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'dynamodb:GetUser'
                - 'dynamodb:PutUser'
              Resource:
                'Fn::Join':
                  - ''
                  - - 'arn:aws:dynamodb:'
                    - Ref: 'AWS::Region'
                    - ':'
                    - Ref: 'AWS::AccountId'
                    - ':table/userTable'

  userTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: inkProductsTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
